### ISSUE TITLE
Crear curso

### ISSUE THREAD

**Issue by MaryJo-jrdev** [HZMDev/Academia#2]
hola, me ha gustado mucho tu módulo y he decidido probar en mi servidor pero da un error a la hora de crear un nuevo curso y resulta imposible.  El resto funciona de diez. 

el log con el error es el siguiente:

```
Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\api.py", line 983, in get
    cache_value = field_cache[record._ids[0]]
KeyError: <NewId 0x21182350648>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\fields.py", line 1138, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\api.py", line 990, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'academia.curso(<NewId 0x21182350648>,).horas_totales'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\api.py", line 983, in get
    cache_value = field_cache[record._ids[0]]
KeyError: <NewId 0x21182350648>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\fields.py", line 1191, in __get__
    value = env.cache.get(record, self)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\api.py", line 990, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: 'academia.curso(<NewId 0x21182350648>,).horas_totales'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\http.py", line 1579, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\service\model.py", line 134, in retrying
    result = func()
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\http.py", line 1608, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\http.py", line 1805, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\addons\website\models\ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\addons\base\models\ir_http.py", line 144, in _dispatch
    result = endpoint(**request.params)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\http.py", line 698, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\addons\web\controllers\dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\models.py", line 6530, in onchange
    snapshot1 = Snapshot(record, nametree)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\models.py", line 6290, in __init__
    self.fetch(name)
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\models.py", line 6300, in fetch
    self[name] = record[name]
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\models.py", line 5851, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "C:\Program Files\Odoo 16.0.20221229\server\odoo\fields.py", line 1194, in __get__
    raise ValueError("Compute method failed to assign %s.%s" % (record, self.name))
ValueError: Compute method failed to assign academia.curso(<NewId 0x21182350648>,).horas_totales

The above server error caused the following client error:
null
```

por cierto, a la hora de facturar ¿cómo se puede hacer para diferenciar a los alumnos de los padres/tutores? ya que estos últimos son los que constan en factura.

**Comment by HZMDev** [comment]
Buenas 👋🏻!! Gracias por usar el módulo jeje, quizás puede ser porque ese curso no tiene asignaturas en él, coméntame si ha podido ser eso, si no me pondré a mirarlo y te digo cuanto antes. Un saludo y feliz año 🎉.

**Comment by MaryJo-jrdev** [comment]
Hola, 
no parece ser ese el problema. He completado todos los submenús de Recursos que son 'asignaturas, profesores, alumnos' y he creado una Evaluación. El tema tiene que ver a la hora de crear un curso. No deja desde el propio menú de Cursos ni tampoco deja desde el submenú Recursos->Asignaturas (curso).

¡Feliz Año Nuevo!

**Comment by HZMDev** [comment]
Buenas, disculpa la tardanza... Ahora mismo estoy con unos fallos en las ejecuciones de  maquinas virtuales por lo que no puedo probarlo... Intentaré resolverlo cuanto antes, gracias 🙂
